name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["nyc", "chi"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --features ${{ matrix.features }} --verbose

    - name: Run tests
      run: cargo test --features ${{ matrix.features }} --verbose
